import type { Metadata } from "next";
import { Geist, Geist_Mono, Leckerli_One, Zain} from "next/font/google";
import "./globals.css";
import NavbarWrapper from "./components/NavbarWrapper"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const leckerLiOne = Leckerli_One({
  variable: "--font-leckerli-one",
  subsets: ["latin"],
  weight: "400",
})

const zain = Zain({
  variable: "--font-zain",
  subsets: ["latin"],
  weight: "700",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zain.variable} ${geistSans.variable} ${leckerLiOne.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarWrapper/>
        {children}
      </body>
    </html>
  );
}
